export const markdownTester: string = [
    '# Markdown: Syntax',
    '',
    '*   [Overview](#overview)',
    '    *   [Philosophy](#philosophy)',
    '    *   [Inline HTML](#html)',
    '    *   [Automatic Escaping for Special Characters](#autoescape)',
    '*   [Block Elements](#block)',
    '    *   [Paragraphs and Line Breaks](#p)',
    '    *   [Headers](#header)',
    '    *   [Blockquotes](#blockquote)',
    '    *   [Lists](#list)',
    '    *   [Code Blocks](#precode)',
    '    *   [Horizontal Rules](#hr)',
    '*   [Span Elements](#span)',
    '    *   [Links](#link)',
    '    *   [Emphasis](#em)',
    '    *   [Code](#code)',
    '    *   [Images](#img)',
    '*   [Miscellaneous](#misc)',
    '    *   [Backslash Escapes](#backslash)',
    '    *   [Automatic Links](#autolink)',
    '',
    '**Note:** This document is itself written using Markdown; you',
    'can [see the source for it by adding \'.text\' to the URL](/projects/markdown/syntax.text).',
    '',
    '----',
    '',
    '## Block Elements',
    '',
    '### Paragraphs and Line Breaks',
    '',
    'A paragraph is simply one or more consecutive lines of text, separated',
    'by one or more blank lines. (A blank line is any line that looks like a',
    'blank line -- a line containing nothing but spaces or tabs is considered',
    'blank.) Normal paragraphs should not be indented with spaces or tabs.',
    '',
    'The implication of the "one or more consecutive lines of text" rule is',
    'that Markdown supports "hard-wrapped" text paragraphs. This differs',
    'significantly from most other text-to-HTML formatters (including Movable',
    'Type\'s "Convert Line Breaks" option) which translate every line break',
    'character in a paragraph into a `<br />` tag.',
    '',
    'When you *do* want to insert a `<br />` break tag using Markdown, you',
    'end a line with two or more spaces, then type return.',
    '',
    '### Headers',
    '',
    'Markdown supports two styles of headers, [Setext] [1] and [atx] [2].',
    '',
    'Optionally, you may "close" atx-style headers. This is purely',
    'cosmetic -- you can use this if you think it looks better. The',
    'closing hashes don\'t even need to match the number of hashes',
    'used to open the header. (The number of opening hashes',
    'determines the header level.)',
    '',
    '### Blockquotes',
    '',
    'Markdown uses email-style `>` characters for blockquoting. If you\'re',
    'familiar with quoting passages of text in an email message, then you',
    'know how to create a blockquote in Markdown. It looks best if you hard',
    'wrap the text and put a `>` before every line:',
    '',
    '> This is a blockquote with two paragraphs. Lorem ipsum dolor sit amet,',
    '> consectetuer adipiscing elit. Aliquam hendrerit mi posuere lectus.',
    '> Vestibulum enim wisi, viverra nec, fringilla in, laoreet vitae, risus.',
    '> ',
    '> Donec sit amet nisl. Aliquam semper ipsum sit amet velit. Suspendisse',
    '> id sem consectetuer libero luctus adipiscing.',
    '',
    '### Lists',
    '',
    'Markdown supports ordered (numbered) and unordered (bulleted) lists.',
    '',
    '*   Red',
    '*   Green',
    '*   Blue',
    '',
    '1.  Bird',
    '2.  McHale',
    '3.  Parish',
    '',
    '### Code Blocks',
    '',
    'Pre-formatted code blocks are used for writing about programming or',
    'markup source code. Rather than forming normal paragraphs, the lines',
    'of a code block are interpreted literally.',
    '',
    '    tell application "Foo"',
    '        beep',
    '    end tell',
    '',
    '## Span Elements',
    '',
    '### Links',
    '',
    'This is [an example](http://example.com/) inline link.',
    '[This link](http://example.net/) has no title attribute.',
    '',
    '### Emphasis',
    '',
    '*single asterisks*',
    '_single underscores_',
    '**double asterisks**',
    '__double underscores__',
    '',
    '### Code',
    '',
    'To indicate a span of code, wrap it with backtick quotes (`` ` ``).',
    'Unlike a pre-formatted code block, a code span indicates code within a',
    'normal paragraph. For example:',
    '',
    'Use the `printf()` function. as my. markdown text',
].join('\n');
